# Generated by Django 4.2.7 on 2025-06-22 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('purpose', models.CharField(choices=[('login', '登录'), ('register', '注册'), ('reset_password', '重置密码'), ('bind_phone', '绑定手机')], max_length=20, verbose_name='用途')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '手机验证码',
                'verbose_name_plural': '手机验证码',
                'db_table': 'phone_verification_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='手机号已验证'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_type',
            field=models.CharField(choices=[('password', '密码登录'), ('phone', '手机验证码'), ('wechat', '微信登录')], default='password', max_length=20, verbose_name='登录方式'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信OpenID'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_unionid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信UnionID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='昵称'),
        ),
        migrations.CreateModel(
            name='WechatUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, unique=True, verbose_name='OpenID')),
                ('unionid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='UnionID')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='微信昵称')),
                ('avatar_url', models.URLField(blank=True, verbose_name='微信头像')),
                ('gender', models.CharField(choices=[('unknown', '未知'), ('male', '男'), ('female', '女')], default='unknown', max_length=10, verbose_name='性别')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='省份')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='国家')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '微信用户信息',
                'verbose_name_plural': '微信用户信息',
                'db_table': 'wechat_user_info',
            },
        ),
    ]
