name: emotion-diary

services:
  # Redis缓存服务
  redis:
    image: redis:7-alpine
    container_name: emotion-diary-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # 主应用服务
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: emotion-diary-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db.sqlite3:/app/backend/db.sqlite3
      - ./logs:/app/logs
      - media_files:/app/backend/media
      - static_files:/app/backend/static
    environment:
      - DEBUG=False
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: emotion-diary-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
      - media_files:/var/www/media:ro
      - static_files:/var/www/static:ro
      - ./backend/static/frontend:/var/www/static/frontend:ro
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
  media_files:
    driver: local
  static_files:
    driver: local

networks:
  default:
    name: emotion-diary-network
